mode: ''
timezone: 'utc'
logging:
  sentry_dsn: ''
  name: sample-ai-chat-app
  handlers:
    file_handler:
      level: DEBUG
      run_mode: 'dev'
      format: '%(asctime)s - %(levelname)s: %(message)s'
      date_format: '%Y-%m-%d %H:%M:%S'
      directory: /var/log/saca/
    stream_handler:
      level: DEBUG
      format: '%(asctime)s - %(levelname)s: %(message)s'
      date_format: '%Y-%m-%d %H:%M:%S'
db:
  conn_str: ''
  db_name: ''