api_path_swagger: /swagger
api_title: MYCHATBOT
api_version: 0.0.0
api_run_host: '127.0.0.1'
api_run_port: 8585
mode: ''
timezone: 'utc'
logging:
  sentry_dsn: ''
  name: sample-ai-chat-app
  handlers:
    file_handler:
      level: DEBUG
      run_mode: 'dev'
      format: '%(asctime)s - %(levelname)s: %(message)s'
      date_format: '%Y-%m-%d %H:%M:%S'
      directory: './logs/saca/'
    stream_handler:
      level: DEBUG
      format: '%(asctime)s - %(levelname)s: %(message)s'
      date_format: '%Y-%m-%d %H:%M:%S'
mongo:
  interactions:
    host: 'mongodb:27017'
    db_name: 'test'
    coll_name: 'interactions'
  messages:
    host: 'mongodb:27017'
    db_name: 'test'
    coll_name: 'messages'
redis:
  interactions:
    host: ''
    port: ''
    db: ''